/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/apple/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Exchange a Sign in with Apple identity token for API tokens, creating
         *     the account on first sign-in. New accounts have no display name yet
         *     (`user.profile_complete` is false); set one with PATCH /me/.
         */
        post: operations["auth_apple_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/dev/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Development only (404 unless DEBUG and DEV_SIGN_IN are on): sign in
         *     with just a display name, so editing can be tested without Apple. The
         *     same name (ignoring case) always gives the same account.
         */
        post: operations["auth_dev_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/edits/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The review queue (pending edits, oldest first) or other edits by status. */
        get: operations["edits_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/edits/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["edits_retrieve"];
        put?: never;
        post?: never;
        /** @description Withdraw your pending edit. */
        delete: operations["edits_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/edits/{id}/vote/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Approve or reject a pending edit. Voting again changes your vote. */
        post: operations["edits_vote_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/films/{tmdb_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["films_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/films/{tmdb_id}/edits/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Propose adding, replacing or removing one of a film's suggestions.
         *     Send multipart form data to include an audio clip.
         */
        post: operations["films_edits_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/films/{tmdb_id}/history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Approved changes to a film's suggestions, newest first. */
        get: operations["films_history_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/films/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["films_search_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The signed-in user's profile. PATCH to set the display name; DELETE to
         *     delete the account (edits stay in the history without a name).
         */
        get: operations["me_retrieve"];
        put?: never;
        post?: never;
        /**
         * @description The signed-in user's profile. PATCH to set the display name; DELETE to
         *     delete the account (edits stay in the history without a name).
         */
        delete: operations["me_destroy"];
        options?: never;
        head?: never;
        /**
         * @description The signed-in user's profile. PATCH to set the display name; DELETE to
         *     delete the account (edits stay in the history without a name).
         */
        patch: operations["me_partial_update"];
        trace?: never;
    };
    "/api/v1/me/edits/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Your own edits, newest first. */
        get: operations["me_edits_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suggestions/{id}/report/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Flag a suggestion as inappropriate for an admin to review. */
        post: operations["suggestions_report_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `add` - Add
         *     * `replace` - Replace
         *     * `remove` - Remove
         * @enum {string}
         */
        ActionEnum: "add" | "replace" | "remove";
        AppleSignIn: {
            identity_token: string;
            authorization_code?: string;
        };
        CastCredit: {
            tmdb_id: number;
            name: string;
            character: string;
        };
        DevSignIn: {
            display_name: string;
        };
        Edit: {
            readonly id: number;
            film: components["schemas"]["FilmSummary"];
            action: components["schemas"]["ActionEnum"];
            replaced_film: components["schemas"]["FilmSummary"] | null;
            proposed_film: components["schemas"]["FilmSummary"] | null;
            explanation?: string;
            readonly audio_url: string | null;
            audio_duration_ms?: number | null;
            language?: components["schemas"]["LanguageEnum"];
            /** @description The proposer's display name; null for seeded edits or deleted accounts. */
            readonly proposer: string | null;
            status?: components["schemas"]["StatusEnum"];
            note?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            resolved_at?: string | null;
            /** @default 0 */
            readonly approvals: number;
            /** @default 0 */
            readonly rejections: number;
            /** @description True = approved, False = rejected, null = hasn't voted. */
            readonly my_vote: boolean | null;
            /** @description Whether the signed-in user proposed this edit (names aren't unique). */
            readonly is_mine: boolean;
        };
        EditCreate: {
            action: components["schemas"]["ActionEnum"];
            /** @description TMDB id of the film to suggest (add/replace). */
            proposed_film?: number;
            /** @description TMDB id of the suggested film to take out (replace/remove). */
            replaced_film?: number;
            explanation?: string;
            /**
             * Format: uri
             * @description A recorded explanation instead of text.
             */
            audio?: string | null;
            language?: components["schemas"]["LanguageEnum"];
        };
        /** @description Full film info; the API adds suggestions (see suggestions.serializers). */
        FilmDetail: {
            tmdb_id: number;
            readonly title: string;
            original_title: string;
            readonly year: number | null;
            runtime?: number | null;
            readonly poster_url: string | null;
            readonly directors: components["schemas"]["PersonCredit"][];
            /** @description The first few billed actors' names. */
            readonly top_cast: string[];
            imdb_id?: string;
            original_language?: string;
            /** Format: date */
            release_date?: string | null;
            readonly overview: string;
            readonly tagline: string;
            readonly genres: string[];
            readonly cast: components["schemas"]["CastCredit"][];
            /** Format: double */
            vote_average?: number;
            vote_count?: number;
            readonly backdrop_url: string | null;
            readonly suggestions: components["schemas"]["Suggestion"][];
            /** @description How many suggestions a film can have; more can be added below this. */
            readonly max_suggestions: number;
        };
        /** @description Compact film info for search results and suggestion cards. */
        FilmSearchResult: {
            tmdb_id: number;
            readonly title: string;
            original_title: string;
            readonly year: number | null;
            runtime?: number | null;
            readonly poster_url: string | null;
            readonly directors: string[];
            /** @description The first few billed actors' names. */
            readonly top_cast: string[];
            /**
             * @description The title the search matched, when it isn't the one being shown
             *     (e.g. the original title of a foreign film); otherwise null.
             */
            readonly matched_title: string | null;
        };
        /** @description Compact film info for search results and suggestion cards. */
        FilmSummary: {
            tmdb_id: number;
            readonly title: string;
            original_title: string;
            readonly year: number | null;
            runtime?: number | null;
            readonly poster_url: string | null;
            readonly directors: string[];
            /** @description The first few billed actors' names. */
            readonly top_cast: string[];
        };
        /**
         * @description * `en` - English
         *     * `fr` - French
         *     * `de` - German
         *     * `es` - Spanish
         *     * `it` - Italian
         *     * `pt` - Portuguese
         * @enum {string}
         */
        LanguageEnum: "en" | "fr" | "de" | "es" | "it" | "pt";
        Me: {
            display_name?: string;
            /**
             * @description False until the user has chosen a display name; the app should ask
             *     for one (pre-filled with the first name Apple shares) before letting
             *     them propose or vote.
             */
            readonly profile_complete: boolean;
            readonly can_moderate: boolean;
            /** Format: date-time */
            readonly date_joined: string;
            readonly pending_edits: number;
            readonly max_pending_edits: number;
        };
        PaginatedEditList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Edit"][];
        };
        PatchedMe: {
            display_name?: string;
            /**
             * @description False until the user has chosen a display name; the app should ask
             *     for one (pre-filled with the first name Apple shares) before letting
             *     them propose or vote.
             */
            readonly profile_complete?: boolean;
            readonly can_moderate?: boolean;
            /** Format: date-time */
            readonly date_joined?: string;
            readonly pending_edits?: number;
            readonly max_pending_edits?: number;
        };
        PersonCredit: {
            tmdb_id: number;
            name: string;
        };
        Report: {
            reason?: string;
        };
        SignInResponse: {
            access: string;
            refresh: string;
            user: components["schemas"]["Me"];
            created: boolean;
        };
        /**
         * @description * `pending` - Pending
         *     * `approved` - Approved
         *     * `auto_approved` - Auto-approved
         *     * `rejected` - Rejected
         *     * `withdrawn` - Withdrawn
         * @enum {string}
         */
        StatusEnum: "pending" | "approved" | "auto_approved" | "rejected" | "withdrawn";
        Suggestion: {
            readonly id: number;
            film: components["schemas"]["FilmSummary"];
            explanation?: string;
            readonly audio_url: string | null;
            audio_duration_ms?: number | null;
            language?: components["schemas"]["LanguageEnum"];
            /**
             * @description The recommender's display name; null for seeded suggestions or
             *     deleted accounts.
             */
            readonly recommended_by: string | null;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        Vote: {
            approve: boolean;
            comment?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_apple_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppleSignIn"];
                "application/x-www-form-urlencoded": components["schemas"]["AppleSignIn"];
                "multipart/form-data": components["schemas"]["AppleSignIn"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResponse"];
                };
            };
        };
    };
    auth_dev_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevSignIn"];
                "application/x-www-form-urlencoded": components["schemas"]["DevSignIn"];
                "multipart/form-data": components["schemas"]["DevSignIn"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResponse"];
                };
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    edits_list: {
        parameters: {
            query?: {
                /** @description Only edits on this TMDB id */
                film?: number;
                /** @description Only edits you didn't propose and haven't voted on */
                needs_my_vote?: boolean;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Default: pending */
                status?: "approved" | "auto_approved" | "pending" | "rejected" | "withdrawn";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedEditList"];
                };
            };
        };
    };
    edits_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Edit"];
                };
            };
        };
    };
    edits_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    edits_vote_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Vote"];
                "application/x-www-form-urlencoded": components["schemas"]["Vote"];
                "multipart/form-data": components["schemas"]["Vote"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Edit"];
                };
            };
        };
    };
    films_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tmdb_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilmDetail"];
                };
            };
        };
    };
    films_edits_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tmdb_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditCreate"];
                "multipart/form-data": components["schemas"]["EditCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["EditCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Edit"];
                };
            };
        };
    };
    films_history_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                tmdb_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedEditList"];
                };
            };
        };
    };
    films_search_list: {
        parameters: {
            query?: {
                /** @description Title to search for */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilmSearchResult"][];
                };
            };
        };
    };
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    me_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMe"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMe"];
                "multipart/form-data": components["schemas"]["PatchedMe"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    me_edits_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedEditList"];
                };
            };
        };
    };
    suggestions_report_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Report"];
                "application/x-www-form-urlencoded": components["schemas"]["Report"];
                "multipart/form-data": components["schemas"]["Report"];
            };
        };
        responses: {
            /** @description No response body */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
