# Generated by Django 6.0.3 on 2026-09-29 15:59

import django.db.models.deletion
import suggestions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("films", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SuggestionEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                (
                    "explanation_audio",
                    models.FileField(
                        blank=True, upload_to=suggestions.models.audio_upload_path
                    ),
                ),
                (
                    "audio_duration_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("pt", "Portuguese"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("add", "Add"),
                            ("replace", "Replace"),
                            ("remove", "Remove"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("auto_approved", "Auto-approved"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "proposed_film",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="films.film",
                    ),
                ),
                (
                    "proposer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggestion_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "replaced_film",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="films.film",
                    ),
                ),
                (
                    "source_film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestion_edits",
                        to="films.film",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                (
                    "explanation_audio",
                    models.FileField(
                        blank=True, upload_to=suggestions.models.audio_upload_path
                    ),
                ),
                (
                    "audio_duration_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("pt", "Portuguese"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="films.film",
                    ),
                ),
                (
                    "suggested_film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_by",
                        to="films.film",
                    ),
                ),
                (
                    "approved_edit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="suggestions.suggestionedit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EditVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approve", models.BooleanField()),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="suggestions.suggestionedit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="suggestions.suggestion",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("suggestion", "reporter"), name="one_report_per_user"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="suggestionedit",
            index=models.Index(
                fields=["status", "created_at"], name="suggestions_status_82860b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="suggestionedit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("action", "add"),
                        ("proposed_film__isnull", False),
                        ("replaced_film__isnull", True),
                        models.Q(
                            models.Q(
                                models.Q(("explanation", ""), _negated=True),
                                ("explanation_audio", ""),
                            ),
                            models.Q(
                                ("explanation", ""),
                                models.Q(("explanation_audio", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        ("action", "replace"),
                        ("proposed_film__isnull", False),
                        ("replaced_film__isnull", False),
                        models.Q(
                            models.Q(
                                models.Q(("explanation", ""), _negated=True),
                                ("explanation_audio", ""),
                            ),
                            models.Q(
                                ("explanation", ""),
                                models.Q(("explanation_audio", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        ("action", "remove"),
                        ("explanation", ""),
                        ("explanation_audio", ""),
                        ("proposed_film__isnull", True),
                        ("replaced_film__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="suggestion_edit_valid_action",
            ),
        ),
        migrations.AddConstraint(
            model_name="suggestion",
            constraint=models.UniqueConstraint(
                fields=("source_film", "suggested_film"),
                name="unique_suggestion_per_film",
            ),
        ),
        migrations.AddConstraint(
            model_name="suggestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_film", models.F("suggested_film")), _negated=True
                ),
                name="suggestion_not_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="suggestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(("explanation", ""), _negated=True),
                        ("explanation_audio", ""),
                    ),
                    models.Q(
                        ("explanation", ""),
                        models.Q(("explanation_audio", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="suggestion_one_explanation",
            ),
        ),
        migrations.AddConstraint(
            model_name="editvote",
            constraint=models.UniqueConstraint(
                fields=("edit", "voter"), name="one_vote_per_edit"
            ),
        ),
    ]
