# Generated by Django 6.0.3 on 2026-09-29 10:17

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.PositiveIntegerField(unique=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("profile_path", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name_plural": "people",
            },
        ),
        migrations.CreateModel(
            name="SkippedTmdbFilm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.PositiveIntegerField(unique=True)),
                ("vote_count", models.PositiveIntegerField(default=0)),
                ("checked_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.PositiveIntegerField(unique=True)),
                ("imdb_id", models.CharField(blank=True, max_length=20)),
                ("original_title", models.CharField(max_length=500)),
                ("original_language", models.CharField(blank=True, max_length=10)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("runtime", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("poster_path", models.CharField(blank=True, max_length=100)),
                ("backdrop_path", models.CharField(blank=True, max_length=100)),
                ("popularity", models.FloatField(default=0)),
                ("vote_count", models.PositiveIntegerField(default=0)),
                ("vote_average", models.FloatField(default=0)),
                (
                    "synced_at",
                    models.DateTimeField(
                        help_text="When this film was last fetched from TMDB."
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True, related_name="films", to="films.genre"
                    ),
                ),
            ],
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="GenreTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="films.genre",
                    ),
                ),
            ],
            options={
                "verbose_name": "genre Translation",
                "db_table": "films_genre_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Credit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("director", "Director"), ("cast", "Cast")],
                        max_length=20,
                    ),
                ),
                ("character", models.CharField(blank=True, max_length=500)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="films.film",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="films.person",
                    ),
                ),
            ],
            options={
                "ordering": ["role", "order"],
            },
        ),
        migrations.CreateModel(
            name="FilmSearchTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_titles",
                        to="films.film",
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.indexes.OpClass(
                            "text", name="gin_trgm_ops"
                        ),
                        name="filmsearchtitle_trgm",
                    ),
                    models.Index(
                        django.contrib.postgres.indexes.OpClass(
                            "text", name="varchar_pattern_ops"
                        ),
                        name="filmsearchtitle_prefix",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("film", "text"), name="unique_film_text"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FilmTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("overview", models.TextField(blank=True)),
                ("tagline", models.CharField(blank=True, max_length=500)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="films.film",
                    ),
                ),
            ],
            options={
                "verbose_name": "film Translation",
                "db_table": "films_film_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language_code", "master"),
                        name="films_film_translation_uniq_lang",
                    )
                ],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name="film",
            index=models.Index(
                fields=["-vote_count"], name="films_film_vote_co_a11eff_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="genretranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="films_genre_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="credit",
            constraint=models.UniqueConstraint(
                fields=("film", "person", "role"), name="unique_film_person_role"
            ),
        ),
    ]
